version: "3.9"

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
      target: scraper
    depends_on:
      - mongodb
    environment:
        DEBUG: "true"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    depends_on:
      - mongodb
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
volumes:
  mongo-data:
